### ISSUE TITLE
android端跑不起来

### ISSUE THREAD

**Issue by py389172739** [wangwei123/weex-vue#1]
直接运行weexpack run android 在安卓上跑不起来，感觉应该是androidIndexURL有问题。
然后运行npm run init  dos下显示android写入INDEX_URL成功，这个是写入到android.config.json这个文件吗？发现虽然显示android写入INDEX_URL成功，但是android.config.json文件并没有被改变

如何才能在安卓端跑起来呢?

**Comment by wangwei123** [comment]
问题已修复，拉取最新代码使用即可
